### PR TITLE
Enable lint

### PR DESCRIPTION
**Pull request by iwahbe**
This enables go listing on this provider.

I'm hoping that merging this change will trigger the `main` workflow and fix https://github.com/pulumi/pulumi-oci/issues/284.

### CODE REVIEW

**Review by blampe — APPROVED** [review]
SDK doesn't look happy -- I re-ran your tests in case it's a flake. Stamping to unblock you once that's resolved. Maybe we just need to regen the SDK?

```
Error: node_modules/@pulumi/pulumi/proto/alias_pb.d.ts(7,23): error TS7016: Could not find a declaration file for module 'google-protobuf'. '/home/runner/work/pulumi-oci/pulumi-oci/sdk/nodejs/node_modules/google-protobuf/google-protobuf.js' implicitly has an 'any' type.
```

**Comment by iwahbe** [comment]
> SDK doesn't look happy -- I re-ran your tests in case it's a flake. Stamping to unblock you once that's resolved. Maybe we just need to regen the SDK?
> 
> ```
> Error: node_modules/@pulumi/pulumi/proto/alias_pb.d.ts(7,23): error TS7016: Could not find a declaration file for module 'google-protobuf'. '/home/runner/work/pulumi-oci/pulumi-oci/sdk/nodejs/node_modules/google-protobuf/google-protobuf.js' implicitly has an 'any' type.
> ```

The schema hasn't changed, so we shouldn't need to regenerate the SDKs. The retry failed though...

**Comment by iwahbe** [comment]
It looks like this was failing universally: https://github.com/pulumi/pulumi-cloudflare/actions/runs/7132092244/job/19422014451?pr=580.

**Comment by guineveresaenger** [comment]
I saw this locally and it resolved once I upgraded to latest node.

**Pull request merged**
